package Package01;

import java.awt.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import java.util.UUID;

import javax.swing.*;

public class SignUpEnd extends JFrame implements ActionListener
{
	private JLabel userId, t, p, pin, userText, passText, service;
	JCheckBox s1, s2, s3, s4, verify, verify1, verify2;
	Font font=new Font("Raleway", Font.BOLD, 20);
	Font f=new Font("Raleway", Font.BOLD, 15);
	Font f1=new Font("Raleway", Font.BOLD, 10);
	Font f2=new Font("Raleway", Font.BOLD, 12);
	private JButton submit;
	String accountNo, name;
	
	public SignUpEnd(String accountNo, String name)
	{
        this.accountNo=accountNo;
        this.name=name;
		
		setTitle("SignUp Page 3 of 3");
		setSize(900,730);
		setLayout(null);
		setLocationRelativeTo(null);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		ImageIcon bgImage=new ImageIcon("Images/pagebg.jpg");
		Image img= bgImage.getImage();
		Image tempImg= img.getScaledInstance(900, 730, Image.SCALE_SMOOTH);
		bgImage= new ImageIcon(tempImg);
		JLabel bglabel=new JLabel("", bgImage, JLabel.CENTER);
		bglabel.setBounds(0, 0, 900, 730);
		add(bglabel);
		
		JPanel panel=new JPanel();
		panel.setLayout(null);
		panel.setBounds(25, 10, 840, 660);
		panel.setBackground(new Color(0, 0, 0, 150));
		bglabel.add(panel);
		
		userId=new JLabel("User ID");
		userId.setBounds(35, 65, 200, 30);
		userId.setFont(font);
		userId.setForeground(Color.WHITE);
		panel.add(userId);
		
		userText=new JLabel("XXXXXXXX");
		userText.setBounds(400, 65, 300, 30);
		userText.setFont(f);
		userText.setForeground(Color.white);
		panel.add(userText);
		
		t=new JLabel("(User ID will be generated by Authority.)");
		t.setBounds(400, 100, 300, 15);
		t.setFont(f1);
		t.setForeground(Color.white);
		panel.add(t);
		
		pin=new JLabel("Password");
		pin.setBounds(35, 125, 200, 30);
		pin.setFont(font);
		pin.setForeground(Color.WHITE);
		panel.add(pin);
		
		passText=new JLabel("XXXX");
		passText.setBounds(400, 125, 300, 30);
		passText.setFont(f);
		passText.setForeground(Color.white);
		panel.add(passText);
		
		p=new JLabel("(Pin will be generated by Authority.)");
		p.setBounds(400, 160, 300, 15);
		p.setFont(f1);
		p.setForeground(Color.white);
		panel.add(p);
		
		
		service=new JLabel("Services Required");
		service.setBounds(35, 190, 200, 30);
		service.setFont(font);
		service.setForeground(Color.WHITE);
		panel.add(service);
		
		s1=new JCheckBox("Net Banking");
		s1.setBounds(400, 210, 200, 30);
		s1.setFont(f);
		s1.setForeground(Color.black);
		panel.add(s1);
		
		s2=new JCheckBox("SMS Service");
		s2.setBounds(610, 210, 200, 30);
		s2.setFont(f);
		s2.setForeground(Color.black);
		panel.add(s2);
		
		s3=new JCheckBox("Email Alert");
		s3.setBounds(400, 255, 200, 30);
		s3.setFont(f);
		s3.setForeground(Color.black);
		panel.add(s3);
		
		s4=new JCheckBox("OTP Verification");
		s4.setBounds(610, 255, 200, 30);
		s4.setFont(f);
		s4.setForeground(Color.black);
		panel.add(s4);
		
		
		
		verify=new JCheckBox("I/We hereby confirm for usage the Bank's Services and agree to them.");
		verify1=new JCheckBox("I/We thereby agree to be subject to and comply with all the provisions of the Terms and Conditions of the Bank.");
		verify2=new JCheckBox("I/We declared that thr above entered details are correct.");
		verify.setBounds(35, 465, 790, 30);
		verify.setFont(f2);
		panel.add(verify);
		verify1.setBounds(35, 500, 790, 30);
		verify1.setFont(f2);
		panel.add(verify1);
		verify2.setBounds(35, 535, 790, 30);
		verify2.setFont(f2);
		panel.add(verify2);
		
		submit=new JButton("Submit");
		submit.setBounds(720, 600, 100, 40);
		submit.setBackground(Color.BLACK);
		submit.setForeground(Color.WHITE);
		submit.addActionListener(this);
		panel.add(submit);
		
		
		setVisible(true);
	}
	@Override
	public void actionPerformed(ActionEvent e) {
		if(e.getSource()==submit) {
			if(!verify.isSelected() || !verify1.isSelected() || !verify2.isSelected()) {
				JOptionPane.showMessageDialog(null, "Please verify all the declaration");
				return;
			}
			Random random=new Random();
			String userId=(String) UUID.randomUUID().toString().toUpperCase().replace("-", "").subSequence(0, 8);
			String pin=""+Math.abs((random.nextLong()%9000L)+1000L);
			String service="";
			if(s1.isSelected()) {
				service=service + " Net Banking";
			}else if(s2.isSelected()) {
				service=service + " SMS";
			}else if(s3.isSelected()) {
				service=service + " Email Alert";
			}else if(s4.isSelected()) {
				service=service + " OTP Verification";
			}
			if(!s1.isSelected() && !s2.isSelected() && !s3.isSelected() && !s4.isSelected()) {
				JOptionPane.showMessageDialog(null, "Atleast one service is required");
				return;
			}
		try {
			Thread.sleep(2000);
			JOptionPane.showMessageDialog(null, "Your User ID is:"+ userId + "\n Pin:" +pin);
			
			ConnectionClass c=new ConnectionClass();
			String Q="insert into signupend values('"+accountNo+"', '"+name+"', '"+userId+"', '"+pin+"', '"+service+"')";
    		String Q2="insert into login values('"+accountNo+"', '"+userId+"', '"+name+"', '"+pin+"')";
    		
    		c.statement.executeUpdate(Q);
    		c.statement.executeUpdate(Q2);
		}catch(Exception e1) {
			System.out.println(e1);
		}
		setVisible(false);
		new Login();
	}
	}
}
